Add support for multiple agreements
BurdaMagazinOrg/module-hm_newsletter pull request #8
Opened 2018-01-18 15:05 UTC by mtodor

We had following problem. Only `datenschutzeinwilligung` agreement was displayed even when site requires more of them.

So following things are improved/changed:
- now more then one agreement is displayed and it's configurable what agreements are supported
- code for displaying agreements that have hidden text is more generic now
- documentation is updated since it's kinda tricky to figure out what should be filled in Block configuration for `Newsletter` field
- schema is added for configuration

Following things should be tested:
- testing of module update
- testing of 0 agreements, 1 agreements and 2+ agreements
- testing of 0 newsletters, 1 newsletter and 2+ newsletters

2018-01-24 12:40 UTC, dbosen requested changes

2018-01-24 12:40 UTC, dbosen commented on README.md
> +4. After that newsletter form should functioning properly.
Please add a description of the "Displayed agreement names" setting

2018-01-24 12:40 UTC, dbosen commented on config/install/hm_newsletter.settings.yml
> +  - 'anspracheerlaubnis'
Add an update hook to prefill this config with the prviewsly hard coded agreement

2018-01-24 12:50 UTC, dbosen commented on src/Form/HmNewsletterNewsletterAdminForm.php
> +    $displayed_agreements = implode('|', $hm_newsletter_settings->get('hm_displayed_agreements'));
This throws an "implode(): Invalid arguments" warnig, when module was updated and the configuration edit screen is used

2018-01-24 12:56 UTC, dbosen commented
While we are working on this project, we should also replace GPL-2.0+ with GPL-2.0-or-later in the composer.json, as expected by packagegist

2018-01-24 15:20 UTC, dbosen submitted a review, later dismissed

2018-01-24 15:22 UTC, dbosen requested changes
see comments above

2018-01-25 11:09 UTC, mtodor commented
To tast BigPipe, just enable module and when you want to test with that functionality disabled, just set cookie and it will be handled by Drupal:
- disable BigPipe: `document.cookie = 'big_pipe_nojs=1';`
- enable BigPipe: `document.cookie = 'big_pipe_nojs=; expires=Thu, 01 Jan 1970 00:00:01 GMT;';`

2018-01-25 11:50 UTC, dbosen approved these changes
fine enough

2018-01-25 11:51 UTC, merged